name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend-eslint:
    name: Run Eslint (frontend)
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: cd frontend && bun run lint

  backend-eslint:
    name: Run Eslint (backend)
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: cd backend && bun run lint

  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-24.04
    needs: frontend-eslint

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Frontend Build
        run: cd frontend && bun run build

  backend-build:
    name: Build Backend
    runs-on: ubuntu-24.04
    needs: backend-eslint

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Prisma Generate
        run: cd backend && bun run prisma:generate

      - name: Run Backend Build
        run: cd backend && bun run build