version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=maozedong
      - MYSQL_DATABASE=chinese-scam
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
  
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:4000"
    environment:
      - DATABASE_URL
      - STRIPE_API_KEY
    networks:
      - default

volumes:
  db:

networks:
  default:
