name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  fe-eslint:
    name: Run Eslint (frontend)
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: cd frontend && bun run lint

  be-eslint:
    name: Run Eslint (backend)
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: cd backend && bun run lint

  fe-unit-test:
    name: Run Unit Test (frontend)
    runs-on: ubuntu-24.04
    needs: fe-eslint

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Frontend Build
        run: cd frontend && bun run test

  fe-build:
    name: Build Frontend
    runs-on: ubuntu-24.04
    needs: fe-eslint

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Frontend Build
        run: cd frontend && bun run build

  be-build:
    name: Build Backend
    runs-on: ubuntu-24.04
    needs: be-eslint

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Prisma Generate
        run: cd backend && bun run prisma:generate

      - name: Run Backend Build
        run: cd backend && bun run build

  fe-coverage:
    name: Run Coverage (frontend)
    runs-on: ubuntu-24.04
    needs: fe-unit-test

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Frontend Test with Coverage
        run: cd frontend && bun run test:coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: frontend/coverage/

